version: "3.8"

services:
  db:
    image: postgres:15.2-alpine
    container_name: postgres
    volumes:
      - ./postgres/create_dbs.sh:/docker-entrypoint-initdb.d/create_dbs.sh
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${DATASOURCE_PASSWORD}
      - POSTGRES_MULTIPLE_DATABASES=users,posts
    ports:
      - "5432:5432"
    networks:
      - main-network

  users:
    build:
      context: ./users
      dockerfile: Dockerfile
    container_name: users
    depends_on:
      - db
    environment:
      - USERS_DATASOURCE_URL=jdbc:postgresql://db:5432/users
      - DATASOURCE_USERNAME
      - DATASOURCE_PASSWORD
    ports:
      - "8080:8080"
    networks:
      - main-network

  posts:
    build:
      context: ./posts
      dockerfile: Dockerfile
    container_name: posts
    depends_on:
      - db
      - users
    environment:
      - POSTS_DATASOURCE_URL=jdbc:postgresql://db:5432/posts
      - DATASOURCE_USERNAME
      - DATASOURCE_PASSWORD
      - USERS_URL=http://users:8080
    ports:
      - "8081:8080"
    networks:
      - main-network

networks:
  main-network:
    driver: bridge

volumes:
  pgdata:
    name: pgdata