apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.posts.serviceName }}
  namespace: {{ .Values.namespace}}
spec:
  selector:
    app: posts
  ports:
    - port: {{ .Values.posts.port }}
      targetPort: {{ .Values.posts.port }}
