apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresql.serviceName }}
  namespace: {{ .Values.namespace}}
spec:
  selector:
    app: postgresql
  ports:
    - port: {{ .Values.postgresql.port }}
      targetPort: {{ .Values.postgresql.port }}