apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.users.serviceName }}
  namespace: {{ .Values.namespace}}
spec:
  selector:
    app: users
  ports:
    - port: {{ .Values.users.port }}
      targetPort: {{ .Values.users.port }}
