apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-deployment
  namespace: k8s-program
  labels:
    app: posts-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: kamronbekrustamov/posts:1.0.1
          ports:
            - containerPort: 8080
          env:
            - name: DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: datasource-secrets
                  key: DATASOURCE_USERNAME
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: datasource-secrets
                  key: DATASOURCE_PASSWORD
            - name: POSTS_DATASOURCE_URL
              value: jdbc:postgresql://postgresql-clusterip-svc:5432/posts
            - name: USERS_URL
              value: http://users-clusterip-svc:8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            failureThreshold: 2
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            failureThreshold: 2
            periodSeconds: 10
            timeoutSeconds: 3
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            failureThreshold: 20
            periodSeconds: 10
            timeoutSeconds: 3