apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
  namespace: k8s-program
  labels:
    app: users-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: kamronbekrustamov/users:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: datasource-secrets
                  key: DATASOURCE_USERNAME
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: datasource-secrets
                  key: DATASOURCE_PASSWORD
            - name: USERS_DATASOURCE_URL
              value: jdbc:postgresql://postgresql-clusterip-svc:5432/users