server:
  port: 8080

spring:
  application:
    name: posts
  datasource:
    url: ${POSTS_DATASOURCE_URL:jdbc:postgresql://localhost:5432/posts}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
  jpa:
    show-sql: true
    format-sql: true
    hibernate:
      format-sql: true
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

users:
  url: ${USERS_URL:http://localhost:8080}